CREATE DATABASE rankedvideos;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
  id UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4(),
  name VARCHAR NOT NULL,
  email VARCHAR UNIQUE NOT NULL,
  password VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS session (
  id UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4(),
  user_id UUID,
  token VARCHAR UNIQUE NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
);
